version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      root-npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: weekly
    groups:
      backend-npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    groups:
      frontend-npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
